
export const latestMatches = [
  {
    id: 1,
    home: 'Barcelona',
    away: 'Real Madrid',
    homeBg: 'linear-gradient(135deg,#a50021,#004d98)',
    awayBg: 'linear-gradient(135deg,#fff9c4,#d4af37)',
    awayColor: '#000',
    time: '5:00 PM',
    location: 'Spain',
    liked: true,
    featured: true,
  },
  {
    id: 2,
    home: 'NY Yorka',
    away: 'NY Yorka',
    homeBg: 'linear-gradient(135deg,#1a237e,#283593)',
    awayBg: 'linear-gradient(135deg,#4a148c,#6a1b9a)',
    awayColor: '#fff',
    time: '5:00 PM',
    location: 'London',
    liked: true,
  },
  {
    id: 3,
    home: 'NY Yorka',
    away: 'NY Yorka',
    homeBg: 'linear-gradient(135deg,#b71c1c,#c62828)',
    awayBg: 'linear-gradient(135deg,#e65100,#ef6c00)',
    awayColor: '#fff',
    time: '5:00 PM',
    location: 'London',
    liked: true,
  },
  {
    id: 4,
    home: 'NY Yorka',
    away: 'NY Yorka',
    homeBg: 'linear-gradient(135deg,#1b5e20,#2e7d32)',
    awayBg: 'linear-gradient(135deg,#006064,#00838f)',
    awayColor: '#fff',
    time: '5:00 PM',
    location: 'London',
    liked: true,
  },
  {
    id: 5,
    home: 'NY Yorka',
    away: 'NY Yorka',
    homeBg: 'linear-gradient(135deg,#4a148c,#6a1b9a)',
    awayBg: 'linear-gradient(135deg,#880e4f,#ad1457)',
    awayColor: '#fff',
    time: '5:00 PM',
    location: 'London',
    liked: true,
  },
];
